context:
  version: "2.26.1"
  numkong_commit: "14daf40059045660775ec39d161f2b51e0a0f2dc"
  fp16_commit: "0a92994d729ff76a58f692d3028ca1b64b145d91"
  stringzilla_commit: "30d3e2129654d8269b3f66726414f9694c834e25"

package:
  name: usearch-python
  version: ${{ version }}

source:
  - url: https://github.com/unum-cloud/USearch/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 0b03a5605efc8468d63cf59c8388e71100463c6708d1136c36f3d6db0de5ab1f
  - url: https://github.com/ashvardanian/NumKong/archive/${{ numkong_commit }}.tar.gz
    sha256: 5ecc85f33ba5cd5cd7e1e41e022597f089ecdc6482f4a51a6482b934cee259db
    target_directory: numkong
  - url: https://github.com/maratyszcza/fp16/archive/${{ fp16_commit }}.tar.gz
    sha256: a91f4770ff9c39f4d72e339c379f566b3bbb359fa66122d85fc0bae3dde7abc7
    target_directory: fp16
  - url: https://github.com/ashvardanian/StringZilla/archive/${{ stringzilla_commit }}.tar.gz
    sha256: d70fb6f4959945e9f791f623de6d6c49dada53431e2987a7a8449cd71b77ff3e
    target_directory: stringzilla

build:
  number: 0
  skip:
    - win
  script:
    env:
      USEARCH_USE_SIMSIMD: "0"
      USEARCH_USE_FP16LIB: "1"
    content:
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools >=42
    - pybind11
    - numpy
  run:
    - python
    - numpy
    - numkong >=7.5.0
    - tqdm

tests:
  - python:
      imports:
        - numkong
        - usearch
        - usearch.index
      pip_check: true
  - script: python -c "import numpy as np; from usearch.index import Index; idx = Index(ndim=3); vec = np.array([0.2, 0.6, 0.4], dtype=np.float32); idx.add(42, vec); matches = idx.search(vec, 1); assert len(matches) == 1 and matches[0].key == 42"

about:
  homepage: https://github.com/unum-cloud/USearch
  summary: Smaller and faster single-file vector search engine from Unum
  repository: https://github.com/unum-cloud/USearch
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - fp16/LICENSE
    - numkong/LICENSE
    - stringzilla/LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
